id: I1BA47112
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:17:54+00:00'
last_modified: '2022-06-07T18:28:03.386263+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9088
  title: རྒྱལ་བའི་ཡིད་འཛིན་བཟོད་པ་ཆོས་ཀྱི་དབང་ཕྱུག་དང་ཀརྨ་དབང་འཛིན་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '2394':
      image_group_id: I1KG9112
      title: ''
      total_pages: 332
      order: 1
      base_file: 2394.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
