id: I1BA47112
legacy_id: P003219
ocr_import_info:
  bdrc_scan_id: W1KG9088
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T16:15:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:18:26.646216+00:00'
last_modified: 2022-09-01 02:18:35.264465
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9088
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9088
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱལ་བའི་ཡིད་འཛིན་བཟོད་པ་ཆོས་ཀྱི་དབང་ཕྱུག་དང་ཀརྨ་དབང་འཛིན་གྱི་རྣམ་ཐར།
  author: གཤེན་མཁས་གྲུབ་ཚུལ་ཁྲིམས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.7584061929098358
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I1KG9112:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9112
      total_pages: 332
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9112.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7584061929098358
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
